import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ChatProvider from "@/context/ChatProvider";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <ChatProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="w-screen min-h-screen noto-sans-normal">
        
            {children}
            </div>
          </ThemeProvider>
        </ChatProvider>
      </body>
    </html>
  );
}
